#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -ex
# -f src/build.xml
IVY_MIRROR_PROP=${IVY_MIRROR_PROP:-http://repo1.maven.org/maven2/}

mkdir -p build
ROOT_DIR = `pwd`

if [ -z "${DO_MAVEN_DEPLOY}" ]; then
  MAVEN_INST_DEPLOY=install
else
  MAVEN_INST_DEPLOY=$DO_MAVEN_DEPLOY
fi
(cd java && mvn clean $MAVEN_INST_DEPLOY -DskipTests)
(cd python && make dist)

rm -rf build
mkdir build/cm_api-${FULL_VERSION}

cd build/cm_api-${FULL_VERSION}
mkdir java python

cp $ROOT_DIR/java/target/cloudera-manager-api-5.3.0*.jar java
cp $ROOT_DIR/python/dist/*.tar.gz python
cp -r $ROOT_DIR/nagios .

cd ..
tar -czf cm_api-${FULL_VERSION}.tar.gz cm_api-${FULL_VERSION}
